name: packetstream
services:
  psclient:
    container_name: psclient
    hostname: psclient
    image: packetstream/psclient:latest
    environment:
      - CID=YOUR_PACKETSTREAM_CID
    labels:
      icon: https://avatars.githubusercontent.com/u/48444771?s=200&v=4
    restart: unless-stopped
    network_mode: bridge
  pswatchtower:
    container_name: pswatchtower
    command:
      - --cleanup
      - --include-stopped
      - --revive-stopped
      - --interval
      - "60"
      - psclient
    hostname: pswatchtower
    image: containrrr/watchtower
    labels:
      icon: https://avatars.githubusercontent.com/u/48444771?s=200&v=4
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    restart: unless-stopped
    network_mode: bridge
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  author: diogow
  category: Finance
  developer: packetstream
  icon: https://avatars.githubusercontent.com/u/48444771?s=200&v=4
  index: /
  port_map: ""
  scheme: http
  store_app_id: packetstream
  title:
    custom: PacketStream
  description:
    en_us: PacketStream lets you earn passive income by sharing your unused internet bandwidth securely and effortlessly.
  tagline:
    en_us: PacketStream Application